### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by zegevlier** [mackenly/cloudflare-magic-linker#1]
Hey!
I love this extension! Have you considered putting it on the Firefox extension store? I tried [loading it from the folder](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) and it looked like everything worked well. I mainly use Firefox, so I'd love to be able to install it natively there.

Here is some documentation on submitting it to the Firefox add-on store: https://extensionworkshop.com/documentation/publish/submitting-an-add-on/

**Comment by mackenly** [comment]
@zegevlier Thank you for bringing this up. I've submitted it to Mozilla and it should be available here once approved. I'll close this issue when it's published: https://addons.mozilla.org/en-US/firefox/addon/cloudflare-magic-linker/ Thanks!

**Comment by mackenly** [comment]
@zegevlier Published 🎉 [https://addons.mozilla.org/en-US/firefox/addon/cloudflare-magic-linker/](https://addons.mozilla.org/en-US/firefox/addon/cloudflare-magic-linker/)
